---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weaveworks
  annotations:
    metadata.weave.works/description: |
      This is the source location for the Weave GitOps Dashboard's helm chart.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
spec:
  interval: 1h
  type: oci
  provider: generic
  secretRef:
    name: ghcr-auth
  url: oci://ghcr.io/weaveworks/charts
