---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-system
resources:
  - arc-helm.yaml
configMapGenerator:
  - name: arc-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=arc-values.yaml
