---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: flux/certificates
  interval: 1h
  retryInterval: 2m
  dependsOn:
    - name: infrastructure
  prune: true
