---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: flux/infrastructure
  interval: 1h
  retryInterval: 2m
  dependsOn:
    - name: sources
  prune: true
