---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: flux/monitoring
  interval: 1h
  retryInterval: 2m
  dependsOn:
    - name: infrastructure
    - name: certificates
  prune: true
  postBuild:
    substitute:
      cluster_name: testing-01
