---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: flux/sources
  # interval is only for periodic reconciliation of the source and the deployed
  # resources to correct for potential configuration drift; any new changes due
  # to an update in the flux-system manifest above will be applied immediately
  interval: 1h
  retryInterval: 2m
  prune: true
