---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  chart:
    spec:
      chart: trivy-operator
      version: '~> 0.22.0'
      sourceRef:
        kind: HelmRepository
        name: aqua-security
        namespace: flux-system
      interval: 1m
  interval: 5m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
