---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: prometheus-system
  labels:
    app: prometheus
spec:
  image: quay.io/prometheus/prometheus:v2.53.1
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 2
  # 7.5 days
  retention: 180h
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
  resources:
    requests:
      memory: 512Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  version: v2.53.1
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
