---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare-system
spec:
  chart:
    spec:
      chart: cloudflare-tunnel
      version: '~> 0.3.0'
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
      interval: 1m
  interval: 5m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true

  values:
    cloudflare:
      tunnelName: n3tuk-minikube-01
      # This Secret is created by Terraform
      secretName: cloudflared-credentials
      ingress:
        # Configure this tunnel to forward all .kube.uk traffic to the
        # nginx-external which will process traffic from external sources
        - hostname: '*.kub3.uk'
          service: http://ingress-nginx-external-controller.ingress-system.svc.cluster.local.

    image:
      tag: 2024.2.1

    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
