---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-system
resources:
  - tunnel-helm.yaml
configMapGenerator:
  - name: tunnel-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=tunnel-values.yaml
