---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: '~> 0.3.0'
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
      interval: 1m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled

  valuesFrom:
    - kind: ConfigMap
      name: tunnel-values
    - kind: ConfigMap
      name: tunnel-overrides
