---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops
  namespace: flux-system
  annotations:
    metadata.weave.works/description: |
      This is the Weave GitOps Dashboard. It provides a simple way to get
      insights into your GitOps workloads.
spec:
  interval: 1h
  chart:
    spec:
      chart: weave-gitops
      version: '~> 4.0.36'
      sourceRef:
        kind: HelmRepository
        name: weaveworks
        namespace: flux-system

  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled

  dependsOn:
    - name: cert-manager
      namespace: certificates-system
    - name: ingress-nginx-internal
      namespace: ingress-system

  valuesFrom:
    - kind: ConfigMap
      name: gitops-values
    - kind: ConfigMap
      name: gitops-ingress
      optional: true
