---
rbac:
  create: true
  clusterRole: true

serviceAccount:
  # Already created by the CRDs file
  create: false

certs:
  issuer:
    create: true
  certificate:
    create: true
    namespace: jaeger-system

resources:
  requests:
    cpu: 100m
    memory: 128Mi
