---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: jaeger-system
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: jaeger
      chart: jaeger-operator
      version: 2.56.0
      interval: 1m
  maxHistory: 50
  interval: 5m
  timeout: 5m
  install:
    crds: CreateReplace
    createNamespace: false
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: enabled

  valuesFrom:
    - kind: ConfigMap
      name: helm-jaeger-operator-values
    - kind: ConfigMap
      name: helm-jaeger-operator-overrides
      optional: true
    - kind: Secret
      name: helm-jaeger-operator-secrets
      optional: true
