---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: elastic
      chart: eck-operator
      version: 2.14.0
      interval: 1m
  maxHistory: 50
  interval: 5m
  timeout: 5m
  install:
    crds: CreateReplace
    createNamespace: false
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: enabled

  valuesFrom:
    - kind: ConfigMap
      name: helm-eck-operator-values
    - kind: ConfigMap
      name: helm-eck-operator-overrides
      optional: true
    - kind: Secret
      name: helm-eck-operator-secrets
      optional: true
