---
# Version of Elasticsearch.
version: 8.15.0

updateStrategy:
  changeBudget:
    maxSurge: 1
    maxUnavailable: 1

podDisruptionBudget:
  spec:
    minAvailable: 2

revisionHistoryLimit: 10

nodeSets:
  - name: masters
    count: 1
    config:
      node.roles: ['master']
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              request:
                memory: 1Gi
                cpu: 200m
              readOnlyRootFilesystem: true
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 32Gi
          storageClassName: local-path
  - name: hot
    count: 2
    config:
      node.roles: ['data_hot', 'data_content', 'ingest']
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              request:
                memory: 1Gi
                cpu: 200m
              readOnlyRootFilesystem: true
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 32Gi
          storageClassName: local-path

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare-production
    external-dns.alpha.kubernetes.io/hostname: elastic.${cluster_name}.${cluster_domain}
  className: nginx-internal
  pathType: Prefix
  hosts:
    - host: elastic.${cluster_name}.${cluster_domain}
      path: /
  tls:
    enabled: true
    secretName: nginx-internal-elasticsearch-tls
