---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: elastic
      chart: eck-elasticsearch
      version: 0.12.0
      interval: 1m
  maxHistory: 50
  interval: 5m
  timeout: 5m
  install:
    crds: CreateReplace
    createNamespace: false
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: enabled

  dependsOn:
    - name: eck-operator

  valuesFrom:
    - kind: ConfigMap
      name: helm-elasticsearch-values
    - kind: ConfigMap
      name: helm-elasticsearch-overrides
      optional: true
    - kind: Secret
      name: helm-elasticsearch-secrets
      optional: true
