---
# Version of Kibana.
version: 8.15.0

spec:
  count: 1
  elasticsearchRef:
    name: eck-elasticsearch
  config:
    server:
      publicBaseUrl: 'https://kibana.${cluster_name}.${cluster_domain}'
  http:
    service:
      spec:
        type: LoadBalancer
nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare-production
    external-dns.alpha.kubernetes.io/hostname: kibana.${cluster_name}.${cluster_domain}
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
  className: nginx-internal
  pathType: Prefix
  hosts:
    - host: kibana.${cluster_name}.${cluster_domain}
      path: /
  tls:
    enabled: true
    secretName: nginx-internal-elasticsearch-tls
