---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-kub3uk-test-letsencrypt
  namespace: certificates-system
spec:
  secretName: certificate-kub3uk-test-letsencrypt
  dnsNames:
    - letsencrypt-test.kub3.uk
  issuerRef:
    name: letsencrypt-cloudflare-test
    kind: ClusterIssuer
