---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: '~> 0.14.0'
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true

  values:
    controller:
      enabled: true
      logLevel: info
      resources:
        request:
          cpu: 100m
          memory: 64Mi

    speaker:
      enabled: true
      logLevel: info
      resources:
        request:
          cpu: 100m
          memory: 64Mi

    crds:
      enabled: true
      validationFailurePolicy: Fail
