---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: flux/applications
  interval: 1h
  retryInterval: 2m
  dependsOn:
    - name: infrastructure
    - name: certificates
    - name: permissions
  prune: true
  postBuild:
    substitute:
      cluster_name: testing-02
      cluster_domain: t.cym-south-1.kub3.uk
