---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: sources
    - name: infrastructure
  interval: 1m
  path: flux/certificates
  prune: true
  validation: client
