---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: certificates-system
spec:
  chart:
    spec:
      chart: cert-manager
      version: '~> 1.14.0'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 1m
  interval: 5m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    installCRDs: true

    dns01RecursiveNameservers: https://cloudflare-dns.com/dns-query
    dns01RecursiveNameserversOnly: true

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0

    resources:
      requests:
        cpu: 100m
        memory: 128Mi

    prometheus:
      enabled: true
      servicemonitor:
        enabled: false

    webhook:
      replicaCount: 1

      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0

      resources:
        requests:
          cpu: 50m
          memory: 64Mi

    cainjector:
      enabled: true
      replicaCount: 1

      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0

      resources:
        requests:
          cpu: 50m
          memory: 64Mi

    startupapicheck:
      enabled: true

      resources:
        requests:
          cpu: 50m
          memory: 64Mi
