---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-dns
  namespace: dns-system
spec:
  chart:
    spec:
      chart: external-dns
      version: '~> 1.14.0'
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 1m
  interval: 5m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true

  values:
    fullnameOverride: cloudflare-dns
    triggerLoopOnEvent: true

    registry: txt
    txtOwnerId: kub3/cloudflare-dns
    txtPrefix: '_%{record_type}.'
    domainFilters:
      - kub3.uk
      - pip3.uk
      - t3st.uk
      - sit3.uk
      - liv3.uk

    provider:
      name: cloudflare

    env:
      - name: CF_API_TOKEN
        value: file:/etc/cloudflare/token
    extraVolumes:
      - name: cloudflare-token
        secret:
          secretName: cloudflare-token
    extraVolumeMounts:
      - name: cloudflare-token
        mountPath: /etc/cloudflare
        readOnly: true

    logLevel: debug
    logFormat: json

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
