---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-podinfo
resources:
  - podinfo-helm.yaml
configMapGenerator:
  - name: podinfo-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=podinfo-values.yaml
