---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo
spec:
  chart:
    spec:
      chart: charts/podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: ingress-nginx-external
      namespace: ingress-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
  values:
    replicaCount: 2

    ui:
      color: '#34577c'
      message: ''
      logo: ''

    ingress:
      enabled: true
      className: nginx-external
      annotations:
        nginx.ingress.kubernetes.io/service-upstream: 'true'
        nginx.ingress.kubernetes.io/upstream-vhost: podinfo.app-podinfo.svc.cluster.local
        external-dns.alpha.kubernetes.io/target: game-unicorn.tunnel.kub3.uk
        external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
      hosts:
        - host: podinfo-testing-01.t3st.uk
          paths:
            - path: /
              pathType: ImplementationSpecific

    resources:
      requests:
        cpu: 10m
        memory: 16Mi
