---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: '~> 6.7.0'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system

  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled

  dependsOn:
    - name: cert-manager
      namespace: certificates-system
    - name: ingress-nginx-external
      namespace: ingress-system

  valuesFrom:
    - kind: ConfigMap
      name: podinfo-values
    - kind: ConfigMap
      name: podinfo-overrides
      optional: true
