---
replicaCount: 2

ingress:
  enabled: true
  className: nginx-external
  annotations:
    external-dns.alpha.kubernetes.io/target: d996c5e4-11da-400a-a8b3-2a7d235675f0.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
  hosts:
    - host: podinfo-${cluster_name}.t3st.uk
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 10m
    memory: 16Mi
