---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-internal-nats
  namespace: app-nats
spec:
  secretName: nginx-internal-nats-tls
  dnsNames:
    - nats.${cluster_name}.${cluster_domain}
  issuerRef:
    name: letsencrypt-cloudflare-production
    kind: ClusterIssuer
