---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-nats
resources:
  - namespace.yaml
  - certificates.yaml
  - nats.yaml
configMapGenerator:
  - name: nats-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=nats-values.yaml
