---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-runners
resources:
  - runners-helm.yaml
configMapGenerator:
  - name: runners-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=runners-values.yaml
