---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: github-runners
  namespace: arc-runners
  annotations:
    metadata.weave.works/description: |
      A Helm chart for deploying an AutoScalingRunnerSet as part of the Actions
      Runner Controller (ARC) for self-hosted runners for GitHub Actions.
  labels:
    app.kubernetes.io/component: runners
    app.kubernetes.io/created-by: github
    app.kubernetes.io/name: github-arc-runners
    app.kubernetes.io/part-of: github-arc
spec:
  interval: 1h
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: github-arc
        namespace: flux-system

  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled

  dependsOn:
    - name: github-arc
      namespace: arc-system

  valuesFrom:
    - kind: ConfigMap
      name: runners-values
    - kind: ConfigMap
      name: runners-name
      optional: true
